/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstallationsRouteImport } from './routes/installations'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksSendblueRouteImport } from './routes/webhooks.sendblue'
import { Route as ThreadsSplatRouteImport } from './routes/threads.$'

const InstallationsRoute = InstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSendblueRoute = WebhooksSendblueRouteImport.update({
  id: '/webhooks/sendblue',
  path: '/webhooks/sendblue',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsSplatRoute = ThreadsSplatRouteImport.update({
  id: '/threads/$',
  path: '/threads/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/installations': typeof InstallationsRoute
  '/threads/$': typeof ThreadsSplatRoute
  '/webhooks/sendblue': typeof WebhooksSendblueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/installations': typeof InstallationsRoute
  '/threads/$': typeof ThreadsSplatRoute
  '/webhooks/sendblue': typeof WebhooksSendblueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/installations': typeof InstallationsRoute
  '/threads/$': typeof ThreadsSplatRoute
  '/webhooks/sendblue': typeof WebhooksSendblueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/installations'
    | '/threads/$'
    | '/webhooks/sendblue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/installations' | '/threads/$' | '/webhooks/sendblue'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/installations'
    | '/threads/$'
    | '/webhooks/sendblue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  InstallationsRoute: typeof InstallationsRoute
  ThreadsSplatRoute: typeof ThreadsSplatRoute
  WebhooksSendblueRoute: typeof WebhooksSendblueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/installations': {
      id: '/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof InstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/sendblue': {
      id: '/webhooks/sendblue'
      path: '/webhooks/sendblue'
      fullPath: '/webhooks/sendblue'
      preLoaderRoute: typeof WebhooksSendblueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$': {
      id: '/threads/$'
      path: '/threads/$'
      fullPath: '/threads/$'
      preLoaderRoute: typeof ThreadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  InstallationsRoute: InstallationsRoute,
  ThreadsSplatRoute: ThreadsSplatRoute,
  WebhooksSendblueRoute: WebhooksSendblueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
